In [132]:
import numpy as np

In [15]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [5]:
#How many negative numbers are there?

print(f"There are {len(a[a < 0])} negative numbers.")

There are 4 negative numbers.


In [6]:
#How many positive numbers are there?

print(f"There are {len(a[a > 0])} positive numbers.")

There are 5 positive numbers.


In [12]:
#How many even positive numbers are there?

b = a[a > 0]
print(f"There are {len(b[b % 2 == 0])} even positive numbers.")

There are 3 even positive numbers.


In [17]:
#If you were to add 3 to each data point, how many positive numbers would there be?

c = a + 3
print(f"There are {len(c[c > 0])} positive numbers.")

There are 10 positive numbers.


In [20]:
#If you squared each number, what would the new mean and standard deviation be?

d = a**2
print(f"New mean: {d.mean()}")
print(f"New standard deviation: {d.std()}")

New mean: 74.0
New standard deviation: 144.0243035046516


In [27]:
#Center the data set.

e = a - 3
print(f"The centered dataset is: {e}")

The centered dataset is: [  1   7   9  20  -5  -4  -3  -3  -3  -9   0 -10]


In [28]:
#Calculate the z-score for each data point.

a_avg = a.mean()
a_std = a.std()

z = (a-a_avg)/a_std
print(f"The z-scores for each data point are: {z}")

The z-scores for each data point are: [ 0.12403473  0.86824314  1.11631261  2.48069469 -0.62017367 -0.49613894
 -0.3721042  -0.3721042  -0.3721042  -1.11631261  0.         -1.24034735]


More Numpy Exercises

In [93]:
## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [32]:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list
sum_of_a = sum(a)
sum_of_a

55

In [33]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list
min_of_a = min(a)
min_of_a

1

In [35]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list
max_of_a = max(a)
max_of_a

10

In [37]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
mean_of_a = sum_of_a / len(a)
mean_of_a

5.5

In [94]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all 
#the numbers in the above list together
prod_of_a = 1
for n in a:
    prod_of_a *= n
prod_of_a

3628800

In [74]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]
squares_of_a = [n**2 for n in a]
squares_of_a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [76]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
odds_in_a = [n for n in a if n%2 != 0]
odds_in_a

[1, 3, 5, 7, 9]

In [77]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.
evens_in_a = [n for n in a if n%2 == 0]
evens_in_a

[2, 4, 6, 8, 10]

In [84]:
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and 
# list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [85]:
b = np.array(b)
b

array([[3, 4, 5],
       [6, 7, 8]])

In [86]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. 
#**Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = b.sum()
sum_of_b

33

In [87]:
# Exercise 2 - refactor the following to use numpy. 
min_of_b = b.min()  
min_of_b

3

In [88]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = b.max()
max_of_b

8

In [92]:
# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = b.mean()
mean_of_b

5.5

In [95]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = b.prod()
product_of_b

20160

In [96]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = b**2
squares_of_b

array([[ 9, 16, 25],
       [36, 49, 64]])

In [101]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = b[b % 2 != 0]
odds_in_b

array([3, 5, 7])

In [103]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = b[b % 2 == 0]
evens_in_b

array([4, 6, 8])

In [104]:
# Exercise 9 - print out the shape of the array b.
print(b.shape)

(2, 3)


In [105]:
# Exercise 10 - transpose the array b.
b2 = np.transpose(b)
b2

array([[3, 6],
       [4, 7],
       [5, 8]])

In [107]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)
b3 = np.arange(3,9).reshape(1,6)
b3

array([[3, 4, 5, 6, 7, 8]])

In [108]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)
b4 = np.arange(3,9).reshape(6,1)
b4

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [109]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]


In [110]:
c = np.array(c)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [114]:
# Exercise 1 - Find the min, max, sum, and product of c.
print(c.min())
print(c.max())
print(c.sum())
print(c.prod())

1
9
45
362880


In [115]:
# Exercise 2 - Determine the standard deviation of c.
c.std()

2.581988897471611

In [116]:
# Exercise 3 - Determine the variance of c.
c.var()

6.666666666666667

In [119]:
# Exercise 4 - Print out the shape of the array c
print(c.shape)

(3, 3)


In [120]:
# Exercise 5 - Transpose c and print out transposed result.
c2 = np.transpose(c)
print(c2)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [123]:
# Exercise 6 - Get the dot product of the array c with c. 
c_times_c = np.dot(c, c)
c_times_c

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [126]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261
c_times_c_tp = c * c2
c_times_c_tp.sum()

261

In [127]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.
c_times_c_tp.prod()

131681894400

In [128]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

In [130]:
d = np.array(d)
d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [133]:
# Exercise 1 - Find the sine of all the numbers in d
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [134]:
# Exercise 2 - Find the cosine of all the numbers in d
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [135]:
# Exercise 3 - Find the tangent of all the numbers in d
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [136]:
# Exercise 4 - Find all the negative numbers in d
d[d < 0]

array([-90, -30, -45, -45])

In [137]:
# Exercise 5 - Find all the positive numbers in d
d[d > 0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [138]:
# Exercise 6 - Return an array of only the unique numbers in d.
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [139]:
# Exercise 7 - Determine how many unique numbers there are in d.
len(np.unique(d))

11

In [141]:
# Exercise 8 - Print out the shape of d.
print(np.shape(d))

(3, 6)


In [142]:
# Exercise 9 - Transpose and then print out the shape of d.
d2 = np.transpose(d)
print(np.shape(d2))

(6, 3)


In [145]:
# Exercise 10 - Reshape d into an array of 9 x 2
d3 = np.reshape(d, (9, 2))
d3

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])